"use client"
import { useEffect, useRef, useState } from "react"

const features = [
  {
    id: "01",
    icon: "⚡",
    title: "AI Brain",
    accent: "var(--amber)",
    glow: "rgba(251,191,36,0.12)",
    border: "rgba(251,191,36,0.2)",
    desc: "A daily intelligence briefing generated by Claude — sharp, specific, execution-focused. Not motivation. Strategy.",
    bullets: ["Claude-powered daily brief", "Context-aware to your business", "Pulsing momentum indicator", "Available every morning"],
  },
  {
    id: "02",
    icon: "🔥",
    title: "Morning Ignition",
    accent: "var(--amber)",
    glow: "rgba(251,191,36,0.08)",
    border: "rgba(251,191,36,0.15)",
    desc: "Set your energy, focus, and intention before the noise starts. A structured 3-minute daily check-in that compounds.",
    bullets: ["Energy + focus calibration", "Daily intention setting", "Yesterday's win capture", "Logs to your history"],
  },
  {
    id: "03",
    icon: "📈",
    title: "Law of 1%",
    accent: "var(--cyan)",
    glow: "rgba(6,182,212,0.10)",
    border: "rgba(6,182,212,0.2)",
    desc: "Track the six daily habits that compound into business results. Small consistency beats occasional intensity every time.",
    bullets: ["Six non-negotiable habits", "Visual progress streaks", "Daily score tracking", "Persistent history log"],
  },
  {
    id: "04",
    icon: "💬",
    title: "Brain Chat",
    accent: "var(--cyan)",
    glow: "rgba(6,182,212,0.08)",
    border: "rgba(6,182,212,0.15)",
    desc: "A Claude-powered strategy assistant that knows the Monte OS framework. Ask about systems, offers, capital, automation.",
    bullets: ["Monte OS framework built in", "Strategy + execution focus", "Persistent conversation", "Powered by Claude Haiku"],
  },
]

export default function Services() {
  const ref = useRef<HTMLDivElement>(null)
  const [inView, setInView] = useState(false)

  useEffect(() => {
    const observer = new IntersectionObserver(([e]) => { if (e.isIntersecting) setInView(true) }, { threshold: 0.1 })
    if (ref.current) observer.observe(ref.current)
    return () => observer.disconnect()
  }, [])

  return (
    <section id="features" style={{ background: "var(--surface-2)", padding: "8rem 0" }}>
      <div style={{ maxWidth: 1280, margin: "0 auto", padding: "0 1.5rem" }}>

        {/* Header */}
        <div style={{ marginBottom: "5rem", maxWidth: 600 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 24 }}>
            <div style={{ height: 1, width: 48, background: "linear-gradient(to right, transparent, var(--amber))" }} />
            <span style={{ fontFamily: "var(--font-mono)", color: "var(--amber)", fontSize: "0.68rem", letterSpacing: "0.4em", textTransform: "uppercase" }}>
              Inside the OS
            </span>
          </div>
          <h2 style={{ fontFamily: "var(--font-display)", fontSize: "clamp(2.5rem,5vw,4.5rem)", lineHeight: 0.92, color: "#f0f0f0", letterSpacing: "-0.02em" }}>
            FOUR TOOLS.<br />
            <span style={{ background: "linear-gradient(135deg, var(--amber), var(--cyan))", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" }}>
              ONE SYSTEM.
            </span>
          </h2>
        </div>

        {/* Grid */}
        <div ref={ref} className="rg-svc">
          {features.map((f, i) => (
            <div
              key={f.id}
              style={{
                background: "var(--surface-2)",
                padding: "3rem",
                opacity: inView ? 1 : 0,
                transition: `all 0.6s ${i * 0.12}s`,
              }}
            >
              {/* Icon + number */}
              <div style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 28 }}>
                <div style={{
                  width: 52,
                  height: 52,
                  background: f.glow,
                  border: `1px solid ${f.border}`,
                  borderRadius: 12,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontSize: "1.25rem",
                }}>
                  {f.icon}
                </div>
                <span style={{ fontFamily: "var(--font-mono)", fontSize: "0.65rem", color: "#333", letterSpacing: "0.2em" }}>
                  {f.id}
                </span>
              </div>

              <h3 style={{ fontFamily: "var(--font-display)", fontSize: "1.75rem", color: "#f0f0f0", marginBottom: 14, letterSpacing: "-0.01em" }}>
                {f.title}
              </h3>
              <p style={{ fontFamily: "var(--font-mono)", color: "#666", fontSize: "0.825rem", lineHeight: 1.7, marginBottom: 24, fontWeight: 300 }}>
                {f.desc}
              </p>

              <ul style={{ listStyle: "none", display: "flex", flexDirection: "column", gap: 8 }}>
                {f.bullets.map(b => (
                  <li key={b} style={{ display: "flex", alignItems: "center", gap: 10, fontSize: "0.8rem", fontFamily: "var(--font-mono)", color: "#555" }}>
                    <span style={{ width: 5, height: 5, borderRadius: "50%", background: f.accent, flexShrink: 0 }} />
                    {b}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div style={{ marginTop: "4rem", textAlign: "center" }}>
          <a href="/os" className="btn-primary" style={{ marginRight: 16 }}>Access the OS →</a>
          <a href="/login" className="btn-outline">Get Early Access</a>
        </div>
      </div>
    </section>
  )
}
